import {
  Atom,
  Aperture,
  Brush,
  Camera,
  CircleDashed,
  Droplets,
  Gem,
  Grip,
  Grid2x2,
  Grid3x3,
  Hexagon,
  Image as ImageIcon,
  Lightbulb,
  Music,
  Network,
  Orbit,
  Palette,
  Pilcrow,
  Shapes,
  Snowflake,
  Sparkles,
  Square,
  Star,
  Thermometer,
  Triangle,
  Type,
  Waves,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const MAP: Record<string, LucideIcon> = {
  image: ImageIcon,
  pilcrow: Pilcrow,
  music: Music,
  square: Square,
  palette: Palette,
  camera: Camera,
  atom: Atom,
  waves: Waves,
  hexagon: Hexagon,
  sparkles: Sparkles,
  droplets: Droplets,
  orbit: Orbit,
  star: Star,
  'circle-dashed': CircleDashed,
  gem: Gem,
  network: Network,
  brush: Brush,
  grid3x3: Grid3x3,
  snowflake: Snowflake,
  aperture: Aperture,
  grip: Grip,
  'grid-2x2': Grid2x2,
  thermometer: Thermometer,
  lightbulb: Lightbulb,
  triangle: Triangle,
  type: Type,
}

export function ToolIcon({ name, className }: { name: string; className?: string }) {
  const Icon = MAP[name] ?? Shapes
  return <Icon className={className} />
}
